name: Assign User

on:
  repository_dispatch:
    types: [slash-command]

jobs:
  assign:
    if: ${{ github.event.client_payload.slash_command.command == 'assign' }}
    runs-on: ubuntu-latest
    steps:
      - name: Assign user
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const user = github.event.client_payload.slash_command.args.unnamed[0];
            if (!user) throw new Error('No user mentioned');
            await github.rest.issues.addAssignees({
              ...context.issue,
              assignees: [user.replace(/^@/, '')]
            });
