name: Labeler

on:
  pull_request:
    types: [opened, synchronize, reopened, labeled, unlabeled]

jobs:
  label:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/labeler@v5
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
